name: Bug report
description: Report a reproducible problem in Focus&go.
title: "[Bug]: "
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for reporting. Short and clear reports help us fix issues faster.
  - type: textarea
    id: summary
    attributes:
      label: What happened?
      description: Describe the observed behavior.
      placeholder: The app crashes when...
    validations:
      required: true
  - type: textarea
    id: steps
    attributes:
      label: Steps to reproduce
      description: Share the minimal sequence to trigger the issue.
      placeholder: |
        1. Open...
        2. Click...
        3. See error...
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: Expected behavior
      placeholder: It should...
    validations:
      required: true
  - type: input
    id: environment
    attributes:
      label: Environment
      description: OS, browser or desktop version, and app version/commit if known.
      placeholder: macOS 14 / Chrome 131 / Focus&go v0.2.0
  - type: textarea
    id: evidence
    attributes:
      label: Logs, screenshots, or recordings
      description: Optional but useful.
