import type { Note, Tag } from "./types";

export const mockTags: Tag[] = [
  {
    id: "t1",
    name: "Projects",
    icon: "folder",
    pinned: true,
    noteCount: 5,
    children: [
      { id: "t1a", name: "Focus&Go", pinned: false, noteCount: 3, children: [] },
      { id: "t1b", name: "Website Redesign", pinned: false, noteCount: 2, children: [] },
    ],
  },
  {
    id: "t2",
    name: "Research",
    icon: "microscope",
    pinned: true,
    noteCount: 8,
    children: [
      { id: "t2a", name: "AI/ML", pinned: false, noteCount: 4, children: [] },
      { id: "t2b", name: "Design Systems", pinned: false, noteCount: 4, children: [] },
    ],
  },
  {
    id: "t3",
    name: "Personal",
    icon: "user",
    pinned: false,
    noteCount: 3,
    children: [],
  },
  {
    id: "t4",
    name: "Reading Notes",
    icon: "book-open",
    pinned: false,
    noteCount: 6,
    children: [
      { id: "t4a", name: "Books", pinned: false, noteCount: 4, children: [] },
      { id: "t4b", name: "Articles", pinned: false, noteCount: 2, children: [] },
    ],
  },
  {
    id: "t5",
    name: "Meetings",
    icon: "calendar",
    pinned: false,
    noteCount: 4,
    children: [],
  },
  {
    id: "t6",
    name: "Ideas",
    icon: "lightbulb",
    pinned: true,
    noteCount: 7,
    children: [],
  },
];

const now = new Date();
const hoursAgo = (h: number) => new Date(now.getTime() - h * 3600000);
const daysAgo = (d: number) => new Date(now.getTime() - d * 86400000);

export const mockNotes: Note[] = [
  {
    id: "n1",
    title: "Design System Architecture",
    content: `# Design System Architecture\n\nA modern design system needs to balance flexibility with consistency. This document outlines the core principles and technical decisions for building a scalable component library.\n\n## Core Principles\n\n- **Composability** - Components should be small, focused, and easily combined\n- **Accessibility** - WCAG 2.1 AA compliance as a baseline\n- **Performance** - Tree-shakeable, lazy-loadable\n- **Theming** - Token-based design that supports multiple themes\n\n## Token Structure\n\nOur tokens follow a three-tier hierarchy:\n\n1. **Global tokens** - Raw values (colors, spacing scale)\n2. **Alias tokens** - Semantic mappings (surface, text, border)\n3. **Component tokens** - Component-specific overrides\n\n### Color System\n\nWe use OKLCH for perceptual uniformity:\n\n| Role | Light | Dark |\n|------|-------|------|\n| Surface | oklch(0.98 0 0) | oklch(0.15 0 0) |\n| Text | oklch(0.15 0 0) | oklch(0.95 0 0) |\n| Accent | oklch(0.55 0.15 250) | oklch(0.65 0.18 250) |\n\n## Component Inventory\n\n- [ ] Button (primary, secondary, ghost, destructive)\n- [x] Input (text, number, search)\n- [x] Select (single, multi)\n- [ ] Dialog (modal, sheet, popover)\n- [x] Typography (heading, body, caption)\n- [ ] Navigation (tabs, sidebar, breadcrumb)\n\n> The component API should feel familiar to developers who have used Radix UI or shadcn/ui.\n\nSee also: [[Component API Guidelines]], [[Token Naming Convention]]`,
    preview: "A modern design system needs to balance flexibility with consistency...",
    tags: ["Research", "Design Systems"],
    pinned: true,
    createdAt: daysAgo(14),
    updatedAt: hoursAgo(2),
    wordCount: 186,
    charCount: 1124,
    paragraphCount: 12,
    imageCount: 0,
    fileCount: 0,
    headings: [
      { level: 1, text: "Design System Architecture", id: "h1" },
      { level: 2, text: "Core Principles", id: "h2" },
      { level: 2, text: "Token Structure", id: "h3" },
      { level: 3, text: "Color System", id: "h4" },
      { level: 2, text: "Component Inventory", id: "h5" },
    ],
    backlinks: [
      { noteId: "n3", noteTitle: "Component API Guidelines" },
      { noteId: "n5", noteTitle: "Weekly Design Review" },
    ],
  },
  {
    id: "n2",
    title: "Focus&Go Product Roadmap Q1",
    content: "Product roadmap for Focus&Go Q1...",
    preview: "Key milestones and deliverables for the Focus&Go product in Q1 2026...",
    tags: ["Projects", "Focus&Go"],
    pinned: true,
    createdAt: daysAgo(30),
    updatedAt: hoursAgo(5),
    wordCount: 342,
    charCount: 2156,
    paragraphCount: 18,
    imageCount: 1,
    fileCount: 2,
    headings: [
      { level: 1, text: "Focus&Go Product Roadmap Q1", id: "h1" },
      { level: 2, text: "Milestones", id: "h2" },
      { level: 2, text: "Key Results", id: "h3" },
    ],
    backlinks: [{ noteId: "n5", noteTitle: "Weekly Design Review" }],
  },
  {
    id: "n3",
    title: "Component API Guidelines",
    content: "Guidelines for component APIs...",
    preview: "Establishing consistent patterns for component props, events, and composition...",
    tags: ["Research", "Design Systems"],
    pinned: false,
    createdAt: daysAgo(10),
    updatedAt: daysAgo(1),
    wordCount: 256,
    charCount: 1580,
    paragraphCount: 14,
    imageCount: 0,
    fileCount: 1,
    headings: [
      { level: 1, text: "Component API Guidelines", id: "h1" },
      { level: 2, text: "Prop Naming", id: "h2" },
      { level: 2, text: "Event Handling", id: "h3" },
    ],
    backlinks: [{ noteId: "n1", noteTitle: "Design System Architecture" }],
  },
  {
    id: "n4",
    title: "Meeting Notes: Kickoff",
    content: "Kickoff meeting notes...",
    preview: "Attendees: Sarah, Mike, Chen. Discussed project timeline and resource allocation...",
    tags: ["Meetings"],
    pinned: false,
    createdAt: daysAgo(7),
    updatedAt: daysAgo(7),
    wordCount: 189,
    charCount: 1120,
    paragraphCount: 8,
    imageCount: 0,
    fileCount: 0,
    headings: [
      { level: 1, text: "Meeting Notes: Kickoff", id: "h1" },
      { level: 2, text: "Agenda", id: "h2" },
      { level: 2, text: "Action Items", id: "h3" },
    ],
    backlinks: [],
  },
  {
    id: "n5",
    title: "Weekly Design Review",
    content: "Weekly design review notes...",
    preview: "Reviewed the new navigation patterns and discussed typography scale adjustments...",
    tags: ["Meetings", "Projects"],
    pinned: false,
    createdAt: daysAgo(2),
    updatedAt: hoursAgo(8),
    wordCount: 210,
    charCount: 1340,
    paragraphCount: 10,
    imageCount: 2,
    fileCount: 0,
    headings: [
      { level: 1, text: "Weekly Design Review", id: "h1" },
      { level: 2, text: "Navigation", id: "h2" },
      { level: 2, text: "Typography", id: "h3" },
    ],
    backlinks: [],
  },
  {
    id: "n6",
    title: "Neural Network Architectures",
    content: "Overview of neural network architectures...",
    preview: "Comparing transformer, CNN, and RNN architectures for different NLP tasks...",
    tags: ["Research", "AI/ML"],
    pinned: false,
    createdAt: daysAgo(21),
    updatedAt: daysAgo(3),
    wordCount: 478,
    charCount: 3200,
    paragraphCount: 22,
    imageCount: 3,
    fileCount: 1,
    headings: [
      { level: 1, text: "Neural Network Architectures", id: "h1" },
      { level: 2, text: "Transformers", id: "h2" },
      { level: 2, text: "CNNs", id: "h3" },
      { level: 2, text: "RNNs", id: "h4" },
    ],
    backlinks: [{ noteId: "n8", noteTitle: "Attention Is All You Need - Notes" }],
  },
  {
    id: "n7",
    title: "The Craft of Writing Software",
    content: "Book notes on writing software...",
    preview: "Chapter 3 highlights the importance of naming things well and keeping functions small...",
    tags: ["Reading Notes", "Books"],
    pinned: false,
    createdAt: daysAgo(45),
    updatedAt: daysAgo(5),
    wordCount: 312,
    charCount: 1980,
    paragraphCount: 16,
    imageCount: 0,
    fileCount: 0,
    headings: [
      { level: 1, text: "The Craft of Writing Software", id: "h1" },
      { level: 2, text: "Chapter 3: Naming", id: "h2" },
      { level: 2, text: "Chapter 4: Functions", id: "h3" },
    ],
    backlinks: [],
  },
  {
    id: "n8",
    title: "Attention Is All You Need - Notes",
    content: "Paper notes...",
    preview: "Key insights from the landmark transformer paper. Multi-head attention mechanism...",
    tags: ["Research", "AI/ML", "Reading Notes"],
    pinned: false,
    createdAt: daysAgo(18),
    updatedAt: daysAgo(4),
    wordCount: 267,
    charCount: 1760,
    paragraphCount: 13,
    imageCount: 1,
    fileCount: 1,
    headings: [
      { level: 1, text: "Attention Is All You Need - Notes", id: "h1" },
      { level: 2, text: "Architecture", id: "h2" },
      { level: 2, text: "Key Insights", id: "h3" },
    ],
    backlinks: [{ noteId: "n6", noteTitle: "Neural Network Architectures" }],
  },
  {
    id: "n9",
    title: "Quick Ideas for Focus Mode",
    content: "Ideas for focus mode...",
    preview: "Ambient sounds, typewriter scrolling, session timers, word count goals...",
    tags: ["Ideas", "Focus&Go"],
    pinned: false,
    createdAt: daysAgo(3),
    updatedAt: hoursAgo(12),
    wordCount: 98,
    charCount: 610,
    paragraphCount: 6,
    imageCount: 0,
    fileCount: 0,
    headings: [{ level: 1, text: "Quick Ideas for Focus Mode", id: "h1" }],
    backlinks: [],
  },
  {
    id: "n10",
    title: "Website Copy Draft",
    content: "Website copy draft...",
    preview: "Hero: 'Write with clarity. Think with structure. Focus & Go.' ...",
    tags: ["Projects", "Website Redesign"],
    pinned: false,
    createdAt: daysAgo(8),
    updatedAt: daysAgo(2),
    wordCount: 156,
    charCount: 980,
    paragraphCount: 8,
    imageCount: 0,
    fileCount: 0,
    headings: [
      { level: 1, text: "Website Copy Draft", id: "h1" },
      { level: 2, text: "Hero Section", id: "h2" },
      { level: 2, text: "Features Section", id: "h3" },
    ],
    backlinks: [],
  },
];

export const trashedNotes: Note[] = [
  {
    id: "tn1",
    title: "Old Meeting Template",
    content: "",
    preview: "An outdated meeting template that was replaced...",
    tags: ["Meetings"],
    pinned: false,
    createdAt: daysAgo(60),
    updatedAt: daysAgo(30),
    trashedAt: daysAgo(5),
    wordCount: 45,
    charCount: 280,
    paragraphCount: 4,
    imageCount: 0,
    fileCount: 0,
    headings: [],
    backlinks: [],
  },
  {
    id: "tn2",
    title: "Scratch Notes - Untitled",
    content: "",
    preview: "Random scratch notes that are no longer needed...",
    tags: [],
    pinned: false,
    createdAt: daysAgo(15),
    updatedAt: daysAgo(10),
    trashedAt: daysAgo(3),
    wordCount: 22,
    charCount: 140,
    paragraphCount: 2,
    imageCount: 0,
    fileCount: 0,
    headings: [],
    backlinks: [],
  },
  {
    id: "tn3",
    title: "Deprecated API Docs",
    content: "",
    preview: "Documentation for the v1 API that has been superseded...",
    tags: ["Projects"],
    pinned: false,
    createdAt: daysAgo(90),
    updatedAt: daysAgo(45),
    trashedAt: daysAgo(1),
    wordCount: 310,
    charCount: 1950,
    paragraphCount: 15,
    imageCount: 0,
    fileCount: 2,
    headings: [],
    backlinks: [],
  },
];
