export const IPC_CHANNELS = [
  'db:tasks:list',
  'db:tasks:add',
  'db:tasks:update',
  'db:tasks:remove',
  'db:tasks:updateStatus',
  'db:tasks:clearAllTags',
  'db:notes:list',
  'db:notes:listTrash',
  'db:notes:create',
  'db:notes:update',
  'db:notes:softDelete',
  'db:notes:restore',
  'db:notes:hardDelete',
  'db:noteTags:list',
  'db:noteTags:create',
  'db:noteTags:update',
  'db:noteTags:remove',
  'db:noteAppearance:get',
  'db:noteAppearance:upsert',
  'db:widgetTodos:list',
  'db:widgetTodos:add',
  'db:widgetTodos:update',
  'db:widgetTodos:resetDone',
  'db:widgetTodos:remove',
  'db:focus:get',
  'db:focus:upsert',
  'db:focusSessions:list',
  'db:focusSessions:start',
  'db:focusSessions:complete',
  'db:diary:list',
  'db:diary:listActive',
  'db:diary:getByDate',
  'db:diary:listByRange',
  'db:diary:listTrash',
  'db:diary:softDeleteByDate',
  'db:diary:restoreByDate',
  'db:diary:markExpiredOlderThan',
  'db:diary:hardDeleteByDate',
  'db:diary:add',
  'db:diary:update',
  'db:spend:listEntries',
  'db:spend:addEntry',
  'db:spend:deleteEntry',
  'db:spend:updateEntry',
  'db:spend:listCategories',
  'db:spend:addCategory',
  'db:spend:updateCategory',
  'db:dashboard:get',
  'db:dashboard:upsert',
  'db:habits:list',
  'db:habits:create',
  'db:habits:update',
  'db:habits:archive',
  'db:habits:restore',
  'db:habits:reorder',
  'db:habits:recordCompletion',
  'db:habits:undoCompletion',
  'db:habits:listLogs',
  'db:habits:computeStreak',
  'db:habits:getDailyProgress',
  'db:habits:getHeatmap',
] as const

export type IpcChannel = (typeof IPC_CHANNELS)[number]

export const isWhitelistedChannel = (channel: string): channel is IpcChannel =>
  (IPC_CHANNELS as readonly string[]).includes(channel)
