export const SYNC_TABLES = {
  tasks: 'sync_tasks',
  notes: 'sync_notes',
  noteTags: 'sync_note_tags',
  noteAppearance: 'sync_note_appearance',
  widgetTodos: 'sync_widget_todos',
  focusSettings: 'sync_focus_settings',
  focusSessions: 'sync_focus_sessions',
  diaryEntries: 'sync_diary_entries',
  spends: 'sync_spends',
  spendCategories: 'sync_spend_categories',
  dashboardLayout: 'sync_dashboard_layout',
  userSubscriptions: 'sync_user_subscriptions',
  featureInstallations: 'sync_feature_installations',
  projects: 'sync_projects',
  projectPeople: 'sync_project_people',
  projectNoteLinks: 'sync_project_note_links',
  taskNoteLinks: 'sync_task_note_links',
  habits: 'sync_habits',
  habitLogs: 'sync_habit_logs',
  books: 'sync_books',
  stocks: 'sync_stocks',
  media: 'sync_media',
  lifeSubscriptions: 'sync_life_subscriptions',
  lifePodcasts: 'sync_life_podcasts',
  lifePeople: 'sync_life_people',
  trips: 'sync_trips',
  lifeDashboardLayout: 'sync_life_dashboard_layout',
  syncedPreferences: 'sync_synced_preferences',
  domainEvents: 'sync_domain_events',
}

export const SYNC_ENTITY_TYPES = Object.keys(SYNC_TABLES)
