import { describe, expect, it } from 'vitest'
import type { TaskItem, FocusSession } from '../../../data/models/types'
import { buildTodayPlan, buildTaskReview, completionRecords, reviewRange, blockedForExecution } from './taskWorkspaceModel'
const now=new Date(2026,9,8,14).getTime()
const task=(id:string,patch:Partial<TaskItem>={}):TaskItem=>({id,title:id,description:'',createdAt:now-86400000,updatedAt:now,pinned:false,isToday:false,status:'todo',priority:null,tags:[],subtasks:[],taskNoteBlocks:[],activityLogs:[],...patch})
const log=(at:number)=>({id:`log-${at}`,type:'status' as const,message:'状态变更为已完成',createdAt:at})
describe('Intentional Today plan',()=>{
 it('keeps overdue suggestions out of the chosen plan',()=>{const urgent=task('late',{dueDate:'2026-10-01'}),planned=task('chosen',{isToday:true});const plan=buildTodayPlan([urgent,planned],undefined,now);expect(plan.ready.map(t=>t.id)).toEqual(['chosen']);expect(plan.candidates.map(t=>t.id)).toEqual(['late']);expect(plan.next?.id).toBe('chosen')})
 it('separates waiting, verification and blocked work from ready-to-focus work',()=>{const items=[task('waiting',{status:'waiting',isToday:true,dueDate:'2026-10-08'}),task('verify',{status:'verify',isToday:true}),task('blocked',{isToday:true,isBlocked:true}),task('ready',{isToday:true})];const plan=buildTodayPlan(items,undefined,now);expect(plan.followUps).toHaveLength(1);expect(plan.verify).toHaveLength(1);expect(plan.blocked).toHaveLength(1);expect(plan.next?.id).toBe('ready')})
 it('does not treat dropped dependencies or missing records as resolved',()=>{const dependent=task('dependent',{dependencyTaskIds:['upstream']});expect(blockedForExecution(dependent,[dependent])).toBe(true);expect(blockedForExecution(dependent,[dependent,task('upstream',{status:'dropped'})])).toBe(true);expect(blockedForExecution(dependent,[dependent,task('upstream',{status:'done'})])).toBe(false)})
 it('uses only current-day completion logs for the done-today shelf',()=>{const items=[task('yesterday',{status:'done',isToday:true,activityLogs:[log(now-86400000)]}),task('today',{status:'done',activityLogs:[log(now-3600000)]})];expect(buildTodayPlan(items,undefined,now).completed.map(r=>r.task.id)).toEqual(['today'])})
})
describe('Period review evidence',()=>{
 it('uses local civil boundaries and Mondays, including month offsets',()=>{const week=reviewRange('week',0,now);expect(new Date(week.start).getDay()).toBe(1);expect(new Date(week.start).getHours()).toBe(0);expect(new Date(reviewRange('month',-1,now).start).getMonth()).toBe(8);expect(new Date(reviewRange('month',0,now).end).getDate()).toBe(1)})
 it('deduplicates task completions within the period and excludes end-boundary events',()=>{const range=reviewRange('week',0,now),items=[task('repeated',{activityLogs:[log(range.start),log(now)]}),task('outside',{activityLogs:[log(range.end)]})];const records=completionRecords(items,range);expect(records).toHaveLength(1);expect(records[0].completedAt).toBe(now);expect(buildTaskReview(items,[],range,now).days.reduce((sum,day)=>sum+day.completed,0)).toBe(1)})
 it('withdraws a reopened result within a period without rewriting earlier periods',()=>{const range=reviewRange('day',0,now),item=task('reopened',{activityLogs:[log(now-1000),{id:'reopen',type:'status',message:'Status changed to Todo',createdAt:now}]});expect(completionRecords([item],range)).toHaveLength(0);item.activityLogs[1].createdAt=range.end;expect(completionRecords([item],range)).toHaveLength(1)})
 it('does not guess a legacy completion date from updatedAt',()=>{const review=buildTaskReview([task('legacy',{status:'done'})],[],reviewRange('day',0,now),now);expect(review.records).toHaveLength(0);expect(review.undatedCompletions).toHaveLength(1)})
 it('uses actual recorded focus duration, never planned duration',()=>{const sessions=[{id:'known',status:'completed',plannedMinutes:50,actualMinutes:12,completedAt:now},{id:'unknown',status:'completed',plannedMinutes:50,completedAt:now},{id:'interrupted',status:'interrupted',plannedMinutes:50,actualMinutes:9,completedAt:now}] as FocusSession[];const review=buildTaskReview([],sessions,reviewRange('day',0,now),now);expect(review.minutes).toBe(12);expect(review.sessions).toHaveLength(2);expect(review.unmeasuredSessions).toBe(1)})
 it('checks blockers outside the current filtered scope',()=>{const dependent=task('dependent',{dependencyTaskIds:['upstream']});expect(buildTaskReview([dependent],[],reviewRange('day',0,now),now,[dependent,task('upstream',{status:'done'})]).blocked).toHaveLength(0)})
})
